version: '3'
services:
    web:
        build: amd64.dockerfile
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        links:
            - db
    db:
        image: "mongo:latest"
